In [61]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.cross_validation import train_test_split
from sklearn.feature_selection import RFE
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
from sklearn.externals import joblib

In [5]:
#data = pd.read_csv("https:\\raw.githubusercontent.com\Vaithyn\Datasets\master\kc_house_data.csv")
data = pd.read_csv("kc_house_data.csv")

In [9]:
print(data.shape)
data.columns

(21613, 21)


Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
id               21613 non-null int64
date             21613 non-null object
price            21613 non-null float64
bedrooms         21613 non-null int64
bathrooms        21613 non-null float64
sqft_living      21613 non-null int64
sqft_lot         21613 non-null int64
floors           21613 non-null float64
waterfront       21613 non-null int64
view             21613 non-null int64
condition        21613 non-null int64
grade            21613 non-null int64
sqft_above       21613 non-null int64
sqft_basement    21613 non-null int64
yr_built         21613 non-null int64
yr_renovated     21613 non-null int64
zipcode          21613 non-null int64
lat              21613 non-null float64
long             21613 non-null float64
sqft_living15    21613 non-null int64
sqft_lot15       21613 non-null int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB


In [12]:
data.describe()

id         price      bedrooms     bathrooms   sqft_living  \
count  2.161300e+04  2.161300e+04  21613.000000  21613.000000  21613.000000   
mean   4.580302e+09  5.400881e+05      3.370842      2.114757   2079.899736   
std    2.876566e+09  3.671272e+05      0.930062      0.770163    918.440897   
min    1.000102e+06  7.500000e+04      0.000000      0.000000    290.000000   
25%    2.123049e+09  3.219500e+05      3.000000      1.750000   1427.000000   
50%    3.904930e+09  4.500000e+05      3.000000      2.250000   1910.000000   
75%    7.308900e+09  6.450000e+05      4.000000      2.500000   2550.000000   
max    9.900000e+09  7.700000e+06     33.000000      8.000000  13540.000000   

           sqft_lot        floors    waterfront          view     condition  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  21613.000000   
mean   1.510697e+04      1.494309      0.007542      0.234303      3.409430   
std    4.142051e+04      0.539989      0.086517      0.766318      0.650743   
min    5.200000e+02      1.000000      0.000000      0.000000      1.000000   
25%    5.040000e+03      1.000000      0.000000      0.000000      3.000000   
50%    7.618000e+03      1.500000      0.000000      0.000000      3.000000   
75%    1.068800e+04      2.000000      0.000000      0.000000      4.000000   
max    1.651359e+06      3.500000      1.000000      4.000000      5.000000   

              grade    sqft_above  sqft_basement      yr_built  yr_renovated  \
count  21613.000000  21613.000000   21613.000000  21613.000000  21613.000000   
mean       7.656873   1788.390691     291.509045   1971.005136     84.402258   
std        1.175459    828.090978     442.575043     29.373411    401.679240   
min        1.000000    290.000000       0.000000   1900.000000      0.000000   
25%        7.000000   1190.000000       0.000000   1951.000000      0.000000   
50%        7.000000   1560.000000       0.000000   1975.000000      0.000000   
75%        8.000000   2210.000000     560.000000   1997.000000      0.000000   
max       13.000000   9410.000000    4820.000000   2015.000000   2015.000000   

            zipcode           lat          long  sqft_living15     sqft_lot15  
count  21613.000000  21613.000000  21613.000000   21613.000000   21613.000000  
mean   98077.939805     47.560053   -122.213896    1986.552492   12768.455652  
std       53.505026      0.138564      0.140828     685.391304   27304.179631  
min    98001.000000     47.155900   -122.519000     399.000000     651.000000  
25%    98033.000000     47.471000   -122.328000    1490.000000    5100.000000  
50%    98065.000000     47.571800   -122.230000    1840.000000    7620.000000  
75%    98118.000000     47.678000   -122.125000    2360.000000   10083.000000  
max    98199.000000     47.777600   -121.315000    6210.000000  871200.000000

In [14]:
data.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [50]:
data.corr()['price'].sort_values(ascending=False)

price            1.000000
sqft_living      0.702035
grade            0.667434
sqft_above       0.605567
sqft_living15    0.585379
bathrooms        0.525138
view             0.397293
sqft_basement    0.323816
bedrooms         0.308350
lat              0.307003
waterfront       0.266369
floors           0.256794
yr_renovated     0.126434
sqft_lot         0.089661
sqft_lot15       0.082447
yr_built         0.054012
condition        0.036362
long             0.021626
id              -0.016762
zipcode         -0.053203
Name: price, dtype: float64

In [51]:
def remove_outlier(df_in, col_name):
    q1 = df_in[col_name].quantile(0.25)
    q3 = df_in[col_name].quantile(0.75)
    iqr = q3-q1 #Interquartile range
    fence_low  = q1-1.5*iqr
    fence_high = q3+1.5*iqr
    df_out = df_in.loc[(df_in[col_name] > fence_low) & (df_in[col_name] < fence_high)]
    return df_out

In [52]:
data_1 = remove_outlier(data,'sqft_living')
data_1 = remove_outlier(data_1,'bedrooms')
data_1 = remove_outlier(data_1,'sqft_above')
data_1.shape

(20145, 21)

In [53]:
y = data_1['price']
y.shape

(20145,)

In [74]:
data_2 = data_1
data_2 = data_2.drop(['id', 'date', 'price'], axis =1)
data_2.shape

(20145, 18)

In [55]:
## Simple model with top 5 columns from corr values
x1 = data_1[['bathrooms','sqft_living','grade','sqft_above','sqft_living15']].copy()
print(x1.shape)
x1.columns

(20145, 5)


Index(['bathrooms', 'sqft_living', 'grade', 'sqft_above', 'sqft_living15'], dtype='object')

In [56]:
x1_train, x1_test, y_train, y_test = train_test_split(x1, y, test_size = 0.3, random_state = 123)

In [57]:
lin_reg1 = LinearRegression()
lin_reg1 = lin_reg1.fit(x1_train, y_train)

In [59]:
test_pred = lin_reg1.predict(x1_test)
train_pred = lin_reg1.predict(x1_train)

In [60]:
print("Model 1 - Top 5 columns from corr values")
print("Test Data - Mean absolute error (MAE):", metrics.mean_absolute_error(y_test,test_pred))
print("Train Data - Mean absolute error (MAE):", metrics.mean_absolute_error(y_train,train_pred))
print("Test Data - Mean squared error (MSE):", np.sqrt(metrics.mean_squared_error(y_test,test_pred)))
print("Train Data - Mean square error (MSE):", np.sqrt(metrics.mean_squared_error(y_train,train_pred)))
print('R-squared (testing data) ', round(lin_reg1.score(x1_test, y_test),3))
print('R-squared (training data) ', round(lin_reg1.score(x1_train, y_train),3))

Model 1 - Top 5 columns from corr values
Test Data - Mean absolute error (MAE): 139143.48376943465
Train Data - Mean absolute error (MAE): 138044.0591180905
Test Data - Mean squared error (MSE): 199108.06440200834
Train Data - Mean square error (MSE): 196059.75465185332
R-squared (testing data)  0.461
R-squared (training data)  0.469


In [81]:
## Moderate model using RFE function selecting top 8 columns
rfe = RFE(lin_reg1, 12)
rfe = rfe.fit(data_2, y)
sum(rfe.support_)

12

In [83]:
x2 = data_2[data_2.columns[rfe.support_]]
print(x2.columns)
x2.shape

Index(['bedrooms', 'bathrooms', 'sqft_living', 'floors', 'waterfront', 'view',
       'condition', 'grade', 'yr_built', 'zipcode', 'lat', 'long'],
      dtype='object')


(20145, 12)

In [84]:
x2_train, x2_test, y_train, y_test = train_test_split(x2, y, test_size = 0.3, random_state = 123)

In [85]:
lin_reg2 = LinearRegression()
lin_reg2 = lin_reg2.fit(x2_train, y_train)
test_pred = lin_reg2.predict(x2_test)
train_pred = lin_reg2.predict(x2_train)

In [87]:
print("Model 2 - Top 12 columns from RFE function")
print("Test Data - Mean absolute error (MAE):", metrics.mean_absolute_error(y_test,test_pred))
print("Train Data - Mean absolute error (MAE):", metrics.mean_absolute_error(y_train,train_pred))
print("Test Data - Mean squared error (MSE):", np.sqrt(metrics.mean_squared_error(y_test,test_pred)))
print("Train Data - Mean square error (MSE):", np.sqrt(metrics.mean_squared_error(y_train,train_pred)))
print('R-squared (testing data) ', round(lin_reg2.score(x2_test, y_test),3))
print('R-squared (training data) ', round(lin_reg2.score(x2_train, y_train),3))

Model 2 - Top 12 columns from RFE function
Test Data - Mean absolute error (MAE): 105834.26347325544
Train Data - Mean absolute error (MAE): 104900.47766370905
Test Data - Mean squared error (MSE): 156201.75901113768
Train Data - Mean square error (MSE): 155100.06197405927
R-squared (testing data)  0.668
R-squared (training data)  0.668


In [88]:
## Moderate model with columns where corr values >.3000
x3 = data_1[['bathrooms','sqft_living','grade','sqft_above','sqft_living15', 'view','sqft_basement','lat','bedrooms', 'sqft_living15']].copy()
print(x3.shape)
x3.columns

(20145, 10)


Index(['bathrooms', 'sqft_living', 'grade', 'sqft_above', 'sqft_living15',
       'view', 'sqft_basement', 'lat', 'bedrooms', 'sqft_living15'],
      dtype='object')

In [89]:
x3_train, x3_test, y_train, y_test = train_test_split(x3, y, test_size = 0.3, random_state = 123)

In [90]:
lin_reg3 = LinearRegression()
lin_reg3 = lin_reg3.fit(x3_train, y_train)
test_pred = lin_reg3.predict(x3_test)
train_pred = lin_reg3.predict(x3_train)

In [91]:
print("Model 3 - Columns which has corr values >.3000")
print("Test Data - Mean absolute error (MAE):", metrics.mean_absolute_error(y_test,test_pred))
print("Train Data - Mean absolute error (MAE):", metrics.mean_absolute_error(y_train,train_pred))
print("Test Data - Mean squared error (MSE):", np.sqrt(metrics.mean_squared_error(y_test,test_pred)))
print("Train Data - Mean square error (MSE):", np.sqrt(metrics.mean_squared_error(y_train,train_pred)))
print('R-squared (testing data) ', round(lin_reg3.score(x3_test, y_test),3))
print('R-squared (training data) ', round(lin_reg3.score(x3_train, y_train),3))

Model 3 - Columns which has corr values >.3000
Test Data - Mean absolute error (MAE): 114532.39766496408
Train Data - Mean absolute error (MAE): 113186.29249609732
Test Data - Mean squared error (MSE): 170949.7329063263
Train Data - Mean square error (MSE): 168657.59880209982
R-squared (testing data)  0.603
R-squared (training data)  0.607


In [92]:
lin_reg1.predict([[2.75, 2810, 9, 1810, 2710]])

array([822920.66957587])

In [93]:
lin_reg2.predict([[4, 2.75, 2810, 1, 0, 0, 4, 9, 1978, 98006, 47.5626, -122.149]])

array([755276.75757691])

In [94]:
lin_reg3.predict([[2.75, 2810, 9, 1810, 2710, 0, 1000, 47.5626, 4, 2710]])

array([731547.25664847])